# Generated by Django 5.0 on 2024-03-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
